[package]
name = "ncd-tools"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap="*"
infer="*"
ncd={ version="0.1.2", git="https://github.com/ens-ds23/ncd" }

